steps:
  # 1. Build Shared LOD Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/backend:latest', '.']
    dir: 'backend'

  # 2. Build Feature Backend (Geruest)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/backend-geruest:latest', '.']
    dir: 'backend_geruest'

  # 3. Build Frontend with Build-Args from Secret Manager
  # This pulls the public API key from Secret Manager during the build
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          -t $_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/frontend:latest \
          --build-arg NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL} \
          --build-arg NEXT_PUBLIC_ANON_KEY=$$PUBLIC_KEY \
          .
    secretEnv: ['PUBLIC_KEY']
    dir: 'frontend'

  # 4. Deploy Shared Backend (Internal)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'wattwert-backend'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/backend:latest'
      - '--region'
      - '${_REGION}'
      - '--port'
      - '8000'
      - '--ingress'
      - 'internal'             # ONLY reachable from within VPC
      - '--no-allow-unauthenticated'
      - '--network'
      - 'default'              # Connect to VPC
      - '--subnet'
      - 'default'              # Direct VPC Egress

  # 5. Deploy Feature Backend (Public Gateway)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'wattwert-backend-geruest'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/backend-geruest:latest'
      - '--region'
      - '${_REGION}'
      - '--port'
      - '8003'
      - '--allow-unauthenticated'
      - '--network'
      - 'default'
      - '--set-env-vars'
      - 'BACKEND_LOD_URL=${_BACKEND_LOD_URL}'
      - '--set-secrets'        # Link private secrets here
      - 'DB_PASSWORD=wattwert-db-pw:latest'

  # 6. Deploy Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'wattwert-frontend'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/frontend:latest'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'

# Pull secrets from Secret Manager to use as build-args
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/PUBLIC_ANON_KEY/versions/latest
      env: 'PUBLIC_KEY'

substitutions:
  _REGION: europe-west1
  _NEXT_PUBLIC_API_URL: "https://api.yourdomain.com" # Use a Load Balancer URL
  _BACKEND_LOD_URL: "https://wattwert-backend-xyz.a.run.app"

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/backend:latest'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/backend-geruest:latest'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/frontend:latest'
