steps:
  # 1. Build Shared LOD Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/backend:latest', '.']
    dir: 'backend'

  # 2. Build Feature Backend (Geruest)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/backend-geruest:latest', '.']
    dir: 'backend_geruest'

  # 3. Build Frontend with Build-Args from Secret Manager
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          -t $_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/frontend:latest \
          --build-arg NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL} \
          --build-arg NEXT_PUBLIC_MAPBOX_TOKEN=$$MAPBOX_TOKEN \
          --build-arg NEXT_PUBLIC_SUPABASE_URL=$$SUPABASE_URL \
          --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=$$SUPABASE_ANON_KEY \
          --build-arg NEXT_RESEND_API_KEY=$$RESEND_KEY \
          .
    secretEnv: ['MAPBOX_TOKEN', 'SUPABASE_URL', 'SUPABASE_ANON_KEY', 'RESEND_KEY']
    dir: 'frontend'

  # 4. Deploy Shared Backend (Internal Only)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'wattwert-backend'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/backend:latest'
      - '--region'
      - '${_REGION}'
      - '--port'
      - '8000'
      - '--ingress'
      - 'internal'
      - '--no-allow-unauthenticated'
      - '--network'
      - 'default'
      - '--subnet'
      - 'default'
      - '--set-secrets'
      - 'SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_ANON_KEY=SUPABASE_ANON_KEY:latest,HF_TOKEN=HF_TOKEN:latest'

  # 5. Deploy Feature Backend (Public Gateway)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'wattwert-backend-geruest'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/backend-geruest:latest'
      - '--region'
      - '${_REGION}'
      - '--port'
      - '8003'
      - '--allow-unauthenticated'
      - '--network'
      - 'default'
      - '--set-env-vars'
      - 'BACKEND_LOD_URL=${_BACKEND_LOD_URL}'
      - '--set-secrets'
      - 'SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_ANON_KEY=SUPABASE_ANON_KEY:latest,HF_TOKEN=HF_TOKEN:latest,DB_PASSWORD=wattwert-db-pw:latest'

  # 6. Deploy Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'wattwert-frontend'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/frontend:latest'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'

# Secrets definitions for the Build Phase (Frontend)
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/SUPABASE_URL/versions/latest
      env: 'SUPABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/SUPABASE_ANON_KEY/versions/latest
      env: 'SUPABASE_ANON_KEY'
    - versionName: projects/$PROJECT_ID/secrets/MAPBOX_TOKEN/versions/latest
      env: 'MAPBOX_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/RESEND_API_KEY/versions/latest
      env: 'RESEND_KEY'

substitutions:
  _REGION: europe-west1
  _NEXT_PUBLIC_API_URL: "https://wattwert-backend-geruest-placeholder-url.a.run.app"
  _BACKEND_LOD_URL: "https://wattwert-backend-placeholder-url.a.run.app"

options:
  logging: CLOUD_LOGGING_ONLY

# All images pushed to Artifact Registry
images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/backend:latest'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/backend-geruest:latest'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/wattwert/frontend:latest'